name: 'Terraform Workflow'

on:
  push:
    branches: [ "master" ]

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}

  TF_VAR_resource_group_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
  TF_VAR_location: ${{ secrets.TF_VAR_LOCATION }}
  TF_VAR_app_service_plan_name: ${{ secrets.TF_VAR_APP_SERVICE_PLAN_NAME }}
  TF_VAR_web_app_name: ${{ secrets.TF_VAR_WEB_APP_NAME }}
  TF_VAR_sql_server_name: ${{ secrets.TF_VAR_SQL_SERVER_NAME }}
  TF_VAR_sql_db_name: ${{ secrets.TF_VAR_SQL_DB_NAME }}
  TF_VAR_sql_admin_name: ${{ secrets.TF_VAR_SQL_ADMIN_NAME }}
  TF_VAR_sql_admin_pass: ${{ secrets.TF_VAR_SQL_ADMIN_PASS }}

jobs: 

    terraform-test:
      runs-on: ubuntu-latest

      steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4


        # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      # Validate Terraform Files
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform  

    terraform-plan:
      runs-on: ubuntu-latest

      needs: [terraform-test]

      steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4
        
        # Login to Azure via Azure CLI
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}


         # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false 


        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init  
        working-directory: ./terraform

        # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform/tfplan

    terraform-apply:
      runs-on: ubuntu-latest

      needs: [terraform-plan]

      steps:
        # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

        # Login to Azure via Azure CLI
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}


        # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false 

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init  
        working-directory: ./terraform


      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./terraform

      - name: Terraform Apply
        run: terraform apply input=false -auto-approve tfplan
        working-directory: ./terraform    
